Repository googleapis/nodejs-automl, pull requests merged in 2019-05, with the labels that each got.

#167 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#168 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#169 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#172 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#173 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#174 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#171 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#175 fix: DEADLINE_EXCEEDED is no longer retried
  src/v1beta1/auto_ml_client_config.json
  src/v1beta1/prediction_service_client_config.json
  synth.metadata
Labels: cla: yes

#177 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1beta1/auto_ml_client_config.json
  src/v1beta1/prediction_service_client_config.json
  synth.metadata
Labels: cla: yes

#178 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#180 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#181 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1beta1/auto_ml_client.js
  src/v1beta1/prediction_service_client.js
  synth.metadata
Labels: cla: yes

#182 docs(samples): fixed comment typo
  samples/vision/automlVisionPredict.js
Labels: cla: yes

#183 feat: add .repo-metadata.json; allows us to generate new docs site
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/quickstart.js
  synth.metadata
Labels: cla: yes, status: blocked

#185 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#187 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#188 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#189 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
