Repository googleapis/nodejs-automl, pull requests merged in 2020-09, with the labels that each got.

#439 build: update kokoro build config
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  samples/test/list_operation_status.test.js
  synth.py
Labels: cla: yes

#443 samples: fix line endings
  samples/vision/automlVisionDataset.js
  samples/vision/automlVisionModel.js
  samples/vision/automlVisionPredict.js
Labels: cla: yes

#445 build: fix typo in synth.py
  synth.py
Labels: cla: yes

#447 samples: disable automl create model tests becuase they have no teardown
  samples/test/automlTranslation.test.js
  samples/test/language_sentiment_analysis_create_model.test.js
  samples/test/language_text_classification_create_model.test.js
  samples/test/translate_create_model.test.js
  samples/test/video-classification-create-model.beta.test.js
  samples/test/video-object-tracking-create-model.beta.test.js
  samples/test/vision_classification_create_model.test.js
  samples/test/vision_object_detection_create_model.test.js
Labels: api: automl, cla: yes, samples

#451 build: update to the latest build and publish configuration
  .gitattributes
  .github/publish.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/presubmit/windows/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .mocharc.js
  README.md
  api-extractor.json
  synth.metadata
Labels: api: automl, cla: yes, context: partial

#454 chore: remove samples/package.json from tracking
  synth.metadata
Labels: api: automl, cla: yes, context: none
