Repository googleapis/nodejs-automl, pull requests merged in 2020-11, with the labels that each got.

#463 build: again pass KOKORO_BUILD_ARTIFACTS_SUBDIR to tests
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: automl, cla: yes, context: none

#466 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/auto_ml_client.ts
  src/v1/prediction_service_client.ts
  src/v1beta1/auto_ml_client.ts
  src/v1beta1/prediction_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: automl, automerge, cla: yes

#465 chore: update synth metadata
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: none

#471 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/auto_ml_client.ts
  src/v1/prediction_service_client.ts
  src/v1beta1/auto_ml_client.ts
  src/v1beta1/prediction_service_client.ts
  synth.metadata
Labels: api: automl, cla: yes, context: partial

#473 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full
