Repository googleapis/nodejs-automl, pull requests merged in 2020-05, with the labels that each got.

#397 feat: check status of long running operation by its name
  src/v1/auto_ml_client.ts
  src/v1/prediction_service_client.ts
  src/v1beta1/auto_ml_client.ts
  src/v1beta1/prediction_service_client.ts
  synth.metadata
  test/gapic_auto_ml_v1.ts
  test/gapic_auto_ml_v1beta1.ts
  test/gapic_prediction_service_v1.ts
  test/gapic_prediction_service_v1beta1.ts
Labels: automerge, cla: yes

#396 fix: clean up synth.py for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#399 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#392 automl: tables-related snippet cleanup
  samples/tables/display-evaluation.v1beta1.js
  samples/tables/export-data-to-bigquery.v1beta1.js
  samples/tables/export-data-to-csv.v1beta1.js
  samples/tables/export-evaluated-examples.v1beta1.js
  samples/tables/get-dataset.v1beta1.js
  samples/tables/get-model-evaluation.v1beta1.js
  samples/tables/get-operation-status.v1beta1.js
  samples/tables/get-table-spec.v1beta1.js
  samples/tables/list-column-specs.v1beta1.js
  samples/tables/list-operation-status.v1beta1.js
  samples/tables/list-table-specs.v1beta1.js
  samples/tables/predict-bq-source-bq-dest.v1beta1.js
  samples/tables/predict-bq-source-gcs-dest.v1beta1.js
  samples/tables/update-column-spec.v1beta1.js
  samples/tables/update-dataset.v1beta1.js
Labels: cla: yes

#391 automl: remove extraneous region tagging
  samples/get_dataset.js
  samples/list_datasets.js
Labels: automerge, cla: yes
