Repository googleapis/nodejs-automl, pull requests merged in 2021-08, with the labels that each got.

#532 chore(nodejs): update client ref docs link in metadata
  .repo-metadata.json
  README.md
Labels: cla: yes, api: automl

#536 fix(build): migrate to using main branch
  .github/.OwlBot.lock.yaml
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  README.md
  samples/README.md
Labels: cla: yes, api: automl

#534 docs: fix typo in sample
  samples/language_text_classification_predict.js
Labels: cla: yes, api: automl, samples

#538 fix(deps): google-gax v2.24.1
  package.json
Labels: cla: yes, automerge, api: automl
